---
title: "Corso di Rmarkdown in Quarto"
subtitle: "Corso ARCA"
author: "Ambra Perugini"
include-in-header: assets/header.html
format: 
  html:
    self-contained: true
    toc: true   
    toc-depth: 3 
    toc-expand: 3 
    code-fold: false 
    message: false
    css: "assets/custom.css"
editor: visual
---

Questo corso ha l'obiettivo di gettare le basi per imparare ad utilizzare Rmarkdown e Quarto per pdf, presentazioni e file htms.

| Date       | Orario        | Aula |
|------------|---------------|------|
| 31/03/2025 | 9:00 - 13:00  | 4R   |
| 01/04/2025 | 9:00 - 13:00  | 4R   |
| 02/04/2025 | 13:00 - 17:00 | 4R   |
| 03/04/2025 | 8:30 - 12:30  | 4M   |
| 04/04/2025 | 9:00 - 13:00  | 4R   |

### Prerequisiti

1. Aver installato R e RStudio [**pagina per il download**](https://posit.co/download/rstudio-desktop/){target="_blank"}
2. Aver installato Latex così da poter compilare i pdf, fondamentale per seguire gli esercizi in aula [**pagina per il download**](https://www.latex-project.org/get/){target="_blank"}
3. Aver controllato che sia RStudio che la compilazione dei PDF funzionino correttamente, per Rmarkdown basta compilare in pdf il file di esempio che viene generato aprendo un nuovo documento.


### Slides

-   **Getting Started with R** - [html](Slides/0.GettingStartedR.html){target="_blank"} - [pdf](Slides/0.GettingStartedR.pdf){target="_blank"}
-   **First Steps in R (part 1)** - [html](Slides/1.1.FirstStepsR-1.html){target="_blank"} - [pdf](Slides/1.1.FirstStepsR-1.pdf){target="_blank"}
-   **First Steps in R (part 2)** - [html](Slides/1.2.FirstStepsR-2.html){target="_blank"} - [pdf](Slides/1.2.FirstStepsR-2.pdf){target="_blank"}
-   **Data Structures (part 1)** - [html](Slides/2.1.DataStruc-1.html){target="_blank"} - [pdf](Slides/2.1.DataStruc-1.pdf){target="_blank"} *(vectors)*
-   **Data Structures (part 2)** - [html](Slides/2.2.DataStruc-2.html){target="_blank"} - [pdf](Slides/2.2.DataStruc-2.pdf){target="_blank"} *(dataframes)*
-   **Data Structures (part 3)** - [html](Slides/2.3.DataStruc-3.html){target="_blank"} - [pdf](Slides/2.3.DataStruc-3.pdf){target="_blank"} *(lists and more)*
-   **Basics of Programming** - [html](Slides/3.Programming.html){target="_blank"} - [pdf](Slides/3.Programming.pdf){target="_blank"} *(conditions, iterations, custom functions)*

### Exercises

*— The following exercises are fundamental, and they importantly integrate concepts from the slides and introduce new functions and methods that you want to know!*

-   **First steps in R** - [html](Exercises/1-Exercises-First-steps.html){target="_blank"}
-   **Vectors** - [html](Exercises/2.1-Exercises-Vectors.html){target="_blank"}
-   **Dataframes** - [html](Exercises/2.2-Exercises-Dataframes.html){target="_blank"}
-   <b>Data <em>nightmare</em> exercise</b> - [html](Exercises/2.3-Exercises-DataScientist.html){target="_blank"}
-   **Programming and more** - [html](Exercises/3-Exercises-ProgrMore.html){target="_blank"}

*— These other exercises are beyond the scope of this introductory course, but they could be stimulating and useful for more advanced R users:*

-   **Creating a word cloud** - [html](Exercises/11-WordCloud.html){target="_blank"}
    -   ::: {style="font-size:14px;"}
        see [here](Exercises/ExampleStrings.html){target="_blank"} some suggestions on manipulating strings
        :::
-   **Monte Carlo simulations for Power analysis** - [html](Exercises/12-MonteCarloSim.html){target="_blank"}
    -   ::: {style="font-size:14px;"}
        see [here](Exercises/ExampleMC.html){target="_blank"} some examples of Monte Carlo simulations
        :::

------------------------------------------------------------------------

::: {style="font-size:11px;"}
GitHub repository associated to the present course website: [https://github.com/ambraperugini/Quarto_ARCA](https://github.com/ambraperugini/Quarto_ARCA){target="_blank"}

:::
